### ISSUE TITLE
monorepo support

### ISSUE THREAD

**Issue by kendinikertenkelebek** [orhun/git-cliff-action#1]
Does it support monorepo? If not, can you do that?

**Comment by orhun** [comment]
Hello!

[git-cliff](https://github.com/orhun/git-cliff) supports monorepos via `--include-path` and `--exclude-path` arguments.You can specify them using [args](https://github.com/orhun/git-cliff-action#input-variables) input variable.

If this is not helpful for you, please give more details about your use case and consider [submitting an issue](https://github.com/orhun/git-cliff/issues/new/choose) to the git-cliff repository.
