### ISSUE TITLE
github integration not working with 1.4.0?

### ISSUE THREAD

**Issue by johnbatclari** [orhun/git-cliff-action#16]
Hi @orhun, I realize github integration is currently experimental, but shouldn't this work? I'm using git-cliff 1.4.0.

```bash
$ GITHUB_TOKEN=$(gh auth token) git cliff --verbose -c config/cliff.toml --include-path "my-service/**"
```
I'm using ` {% if commit.github.username %} (by [@{{ commit.github.username }}](<GITHUB>{{ commit.github.username }}))` in my macro commit but the github integration is not getting picked up. 

If I add the `--github-repo user/repo` args, I get the following:
```shell
error: unexpected argument '--github-repo' found

  tip: to pass '--github-repo' as a value, use '-- --github-repo'

Usage: git-cliff [FLAGS] [OPTIONS] [--] [RANGE]
```
The docs mention building from source but it sounds as if that's optional. Thoughts?

**Comment by orhun** [comment]
Hello!

The action is not using the git version of `git-cliff` - and I haven't released this feature.

You can install `git-cliff` from source to try it out in your workflow:

```sh
$ cargo install --git https://github.com/orhun/git-cliff git-cliff

$ git cliff --github-repo ...
```

Or please wait for the new release in a couple of weeks 🐻

**Comment by johnbatclari** [comment]
Sounds good, thanks @orhun! I'll try it out locally and wait for the action to be updated with the new release.
