### ISSUE TITLE
Updating the `git-cliff` version to support `features_always_bump_minor` and `breaking_always_bump_major`

### ISSUE THREAD

**Issue by JKRhb** [orhun/git-cliff-action#20]
I am using the `git-cliff-action` in a GitHub Actions workflow where I was expecting `git-cliff` to support the configuration options `features_always_bump_minor´ and `breaking_always_bump_major`. However, these two options have been added in a [more recent `git-cliff` release](https://github.com/orhun/git-cliff/releases/tag/v2.2.0) than the one `git-cliff-action` is currently depending on.

Would it be possible to update `git-cliff` to a version >= 2.2.0 to add support for the configuration options? In any case: Thank you very much for a really great tool :)

**Comment by orhun** [comment]
Done, thanks for the reminder and kind words <3

**Comment by JKRhb** [comment]
Thanks a lot! :)
