### ISSUE TITLE
Issues with `orhun/git-cliff-action` after upgrade from v3.3.0 to the latest v4

### ISSUE THREAD

**Issue by dbelyaev** [orhun/git-cliff-action#29]
I switched from v3 to v4 and now fails with (output from act tool):
```
Run Main Download git-cliff
🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/git-cliff-composite-0.sh] user= workdir=
| /var/run/act/workflow/git-cliff-composite-0.sh: line 2: /var/run/act/actions/orhun-git-cliff-action@v4.0.0/install.sh: Permission denied
```

**Comment by orhun** [comment]
Hey, v4 no longer uses Docker for this action. You can use the [docker image directly](https://hub.docker.com/r/orhunp/git-cliff) if you wish to keep using it :)

As for `act`, I'm not sure what's going on there. Can you share a minimal reproducible example?

**Comment by dbelyaev** [comment]
Hi, @orhun, and thank you for your quick response!

I have created a simple repository with an example of issues that arise after upgrading from **v3.3.0** to **v4**.
You can find the demo repository here: [dbelyaev/gitcliff-demo](https://github.com/dbelyaev/gitcliff-demo).

This repository includes a simple workflow called [cd-release-draft.yml](https://github.com/dbelyaev/gitcliff-demo/blob/84de18176f5fbf7e08bd270f05d88660fa4b2b2c/.github/workflows/cd-release-draft.yml) that runs on a `push` to the `main` branch and does the following:

1. It tries to find an upcoming release version based on merge commit message and outputs it for other steps (example: `v0.0.1`)
https://github.com/dbelyaev/gitcliff-demo/blob/84de18176f5fbf7e08bd270f05d88660fa4b2b2c/.github/workflows/cd-release-draft.yml#L18-L27

2. It calls the `orhun/git-cliff-action` action to generate a changelog.
https://github.com/dbelyaev/gitcliff-demo/blob/84de18176f5fbf7e08bd270f05d88660fa4b2b2c/.github/workflows/cd-release-draft.yml#L30-L53

3. It tries to create a new draft for GitHub release using the changelog generated by the `generate-changelog` step (git-cliff).
https://github.com/dbelyaev/gitcliff-demo/blob/84de18176f5fbf7e08bd270f05d88660fa4b2b2c/.github/workflows/cd-release-draft.yml#L56-L76

Initial [release/v0.0.1 run](https://github.com/dbelyaev/gitcliff-demo/actions/runs/10628833467) (using orhun/git-cliff-action@v3.3.0) went as planned resulting in [nice changelog and github release](https://github.com/dbelyaev/gitcliff-demo/releases/tag/v0.0.1).

The second [release/v0.0.2 run](https://github.com/dbelyaev/gitcliff-demo/actions/runs/10628926217) (using orhun/git-cliff-action@v4.0.0) tried to generate changelog but failed to generate changelog resulting in an [empty release](https://github.com/dbelyaev/gitcliff-demo/releases/tag/untagged-93e395b6509e8b02c69e).

[Here is an output](https://github.com/dbelyaev/gitcliff-demo/actions/runs/10628926217/job/29464721375) of action run gitcliff v4.

Let me know if you have any further questions or concerns.

**Comment by dbelyaev** [comment]
UPDATE.
I was suspicious that maybe experimental GitHub integration feature is the cause of the problem, so I removed:
```
--github-repo ${{ github.repository }}
```
And did another [run](https://github.com/dbelyaev/gitcliff-demo/actions/runs/10631341083/job/29472036202) and it is still failing to generate changelog.

Some output:
```
+ LOCATION=https://github.com/orhun/git-cliff/releases/download/v2.5.0/git-cliff-2.5.0-x86_64-unknown-linux-gnu.tar.gz
+ [[ ! -e git-cliff-2.5.0-x86_64-unknown-linux-gnu.tar.gz ]]
+ curl --silent --show-error --fail --location --output git-cliff-2.5.0-x86_64-unknown-linux-gnu.tar.gz https://github.com/orhun/git-cliff/releases/download/v2.5.0/git-cliff-2.5.0-x86_64-unknown-linux-gnu.tar.gz
+ tar -xf git-cliff-2.5.0-x86_64-unknown-linux-gnu.tar.gz
+ mv git-cliff-2.5.0/git-cliff .
Run /home/runner/work/_actions/orhun/git-cliff-action/8720f565e14eb8f89de1c1399d3a5f75027957ff/run.sh --config=cliff.toml --verbose \ --unreleased \ --tag v0.0.3
+ set -o noglob
++ stat -c %u:%g .
+ owner=1001:127
++ id -u
+ chown -R 1001 .
+ OUTPUT=git-cliff/CHANGELOG.md
++ dirname git-cliff/CHANGELOG.md
+ mkdir -p git-cliff
mkdir: cannot create directory ‘git-cliff’: File exists
++ echo --config=cliff.toml --verbose ' --unreleased' ' --tag' v0.0.3
++ xargs
+ args='--config=cliff.toml --verbose --unreleased --tag v0.0.3'
+ GIT_CLIFF_OUTPUT=git-cliff/CHANGELOG.md
+ ./git-cliff --config=cliff.toml --verbose --unreleased --tag v0.0.3
 DEBUG git_cliff > No GitHub remote is set, using remote: dbelyaev/gitcliff-demo
 DEBUG git_cliff_core::changelog > Adding remote data...
 DEBUG git_cliff_core::changelog > Processing the commits...
 DEBUG git_cliff_core::changelog > Processing the releases...
 ERROR git_cliff                 > IO error: `Not a directory (os error 20)`
+ exit_code=1
++ mktemp
+ CONTEXT=/tmp/tmp.k5OrYfEyFq
+ GIT_CLIFF_OUTPUT=/tmp/tmp.k5OrYfEyFq
+ ./git-cliff --config=cliff.toml --verbose --unreleased --tag v0.0.3 --context
 DEBUG git_cliff > No GitHub remote is set, using remote: dbelyaev/gitcliff-demo
 DEBUG git_cliff_core::changelog > Adding remote data...
 DEBUG git_cliff_core::changelog > Processing the commits...
 DEBUG git_cliff_core::changelog > Processing the releases...
+ cat git-cliff/CHANGELOG.md
cat: git-cliff/CHANGELOG.md: Not a directory
+ chown -R 1001:127 .
+ echo 'content<<EOF'
+ cat git-cliff/CHANGELOG.md
cat: git-cliff/CHANGELOG.md: Not a directory
+ echo EOF
+ echo changelog=git-cliff/CHANGELOG.md
++ jq -r '.[0].version' /tmp/tmp.k5OrYfEyFq
+ echo version=v0.0.3
+ echo exit_code=1
```

**Comment by orhun** [comment]
Thanks for the detailed debugging of the issue!

I see a couple of errors in the logs:

> 2024-08-30T07:51:23.2261098Z  ERROR git_cliff                 > IO error: `Not a directory (os error 20)`

My first suspicion is:

>  \+ GIT_CLIFF_OUTPUT=git-cliff/CHANGELOG.md

Does that directory really exist?

**Comment by orhun** [comment]
Also, cc @M0NsTeRRR since he implemented this new binary functionality :)

**Comment by orhun** [comment]
One other error is:

>  ERROR git_cliff_core::remote    > Request error: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/pulls/pulls#list-pull-requests","status":"403"}
> DEBUG git_cliff_core::remote    > Error while fetching page: JsonError(Error("invalid type: map, expected a sequence", line: 1, column: 0))

Maybe there is also a [permission issue](https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac)? Can you try setting up some permissions in the workflow and try again maybe?

**Comment by M0NsTeRRR** [comment]
Hello,

Thanks for the notification @orhun.

@dbelyaev could you test with github action `m0nsterrr/git-cliff-action@v1.5.0` ?
The script could not create the git-cliff folder because a binary with the same name exists in the current directory.

**Comment by orhun** [comment]
Awesome, thanks for the quick fix! <3

**Comment by orhun** [comment]
`v4`/`v4.0.1` is released, it should work fine now. @dbelyaev let me know if you experience any other issues!
