### ISSUE TITLE
Re-license under the MIT + Apache 2.0 license

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff-action#32]
`git-cliff` has been re-licensed under MIT + Apache 2.0 license in [#165](https://github.com/orhun/git-cliff/issues/165) and `git-cliff-action` was sitting with GPL-3.0 for a while. So let's re-license it :)

- [x] @orhun
- [x] @M0NsTeRRR
- [x] @aburgel
- [x] @clementnuss
- [x] @Gnyblast
- [x] @mloberg
- [x] @chamini2
- [x] @nhedger

Please leave a comment to this issue stating that you consent to the license change or indicate your objection if you do not agree with the new license terms. For example:

- ✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.
- ❌ I object to the proposed license change and do not consent to my work on git-cliff being licensed under either the MIT or Apache 2.0 license.

Thank you for your contributions to the project and your attention to the matter! 🐻

**Comment by orhun** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by Gnyblast** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by M0NsTeRRR** [comment]
Of course MIT/Apache > GPL :)

✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by chamini2** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by clementnuss** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by orhun** [comment]
Re-licensed in 9f34d775d33d958da57115f4a2c7cfe9cff4a464 - thanks everyone for their contribution & attention <3
