### ISSUE TITLE
Cannot install git-cliff when ref action in self-hosted runners

### ISSUE THREAD

**Issue by gdagil** [orhun/git-cliff-action#33]
Hello!
Thank you for your product. I’ve been considering integrating it into my projects using GitHub Actions and encountered an issue.

I have my own act_runner for self-hosted Gitea. Since most of the environment variables here are the same as those on GitHub runners, an error occurs when running your action stating that the request cannot be executed - 401 response from api.github.com server.

I believe it would be better to exclude setting the authorization header when downloading the package in the line provided below.
https://github.com/orhun/git-cliff-action/blob/9f34d775d33d958da57115f4a2c7cfe9cff4a464/install.sh#L27

Attaching the act_runner logs:
```bash
1 | + case "${RUNNER_OS}" in
-- | --
2 | + OS=unknown-linux-gnu
3 | + case "${RUNNER_ARCH}" in
4 | + ARCH=x86_64
5 | + RELEASE_URL=https://api.github.com/repos/orhun/git-cliff/releases/latest
6 | + [[ v2.5.0 != \l\a\t\e\s\t ]]
7 | + RELEASE_URL=https://api.github.com/repos/orhun/git-cliff/releases/tags/v2.5.0
8 | ++ curl --silent --show-error --fail --header 'authorization: Bearer ***' --header 'Cache-Control: no-cache, must-revalidate' https://api.github.com/repos/orhun/git-cliff/releases/tags/v2.5.0
9 | curl: (22) The requested URL returned error: 401
10 | + RELEASE_INFO=
11 | ++ echo ''
12 | ++ jq --raw-output .tag_name
13 | /var/run/act/actions/orhun-git-cliff-action@v4/install.sh: line 30: jq: command not found
14 | + TAG_NAME=
15 | + TARGET=git-cliff--x86_64-unknown-linux-gnu.tar.gz
16 | ++ echo ''
17 | ++ jq --raw-output '.assets[].browser_download_url'
18 | /var/run/act/actions/orhun-git-cliff-action@v4/install.sh: line 34: jq: command not found
19 | ++ grep 'git-cliff--x86_64-unknown-linux-gnu.tar.gz$'
20 | + LOCATION=
21 | + mkdir -p ./bin
22 | + [[ ! -e git-cliff--x86_64-unknown-linux-gnu.tar.gz ]]
23 | + curl --silent --show-error --fail --location --output git-cliff--x86_64-unknown-linux-gnu.tar.gz ''
24 | curl: (3) URL using bad/illegal format or missing URL
25 | + tar -xf git-cliff--x86_64-unknown-linux-gnu.tar.gz
26 | tar: git-cliff--x86_64-unknown-linux-gnu.tar.gz: Cannot open: No such file or directory
27 | tar: Error is not recoverable: exiting now
28 | + mv git-cliff-/git-cliff ./bin/git-cliff
29 | mv: cannot stat 'git-cliff-/git-cliff': No such file or directory
```

**Comment by gdagil** [comment]
Of course, it's possible to use installation via pip, but I would prefer not to add an additional step for installing Python and instead use a compiled release

**Comment by orhun** [comment]
Hello, thanks for reporting and sorry for the delayed response!

> I believe it would be better to exclude setting the authorization header when downloading the package in the line provided below.

I'm not sure if removing that would be a problem, but I presume it should be fine since we are executing from the GitHub context anyways. Or maybe we can support an option to disable it somehow.

cc @M0NsTeRRR - what do you think?

**Comment by M0NsTeRRR** [comment]
Hello,

As mentioned in the script, the token is used to increase GitHub API limits: https://github.com/orhun/git-cliff-action/blob/9f34d775d33d958da57115f4a2c7cfe9cff4a464/install.sh#L22-L25
Source : https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users

For now, you can pass a GitHub token in your Gitea CI as `GITHUB_TOKEN`.

We could add an option to disable the authorization header in cases where someone is using Gitea or an other CI compatible with Github action and doesn't need to worry about rate limits.

**Comment by orhun** [comment]
> We could add an option to disable the authorization header in cases where someone is using Gitea or an other CI compatible with Github action and doesn't need to worry about rate limits.

Yup, sounds good. It should be disabled as default though.

**Comment by gdagil** [comment]
Maybe you should just make sure that the environment variable exists? 

Since there is no such variable in gitea act_runner and GITEA_TOKEN is used

**Comment by M0NsTeRRR** [comment]
> Maybe you should just make sure that the environment variable exists?
> 
> Since there is no such variable in gitea act_runner and GITEA_TOKEN is used

If Gitea CI doesn't use it we could yeah, I'm not familiar with it :)

**Comment by orhun** [comment]
Actually yeah, that sounds more reasonable.

**Comment by M0NsTeRRR** [comment]
@gdagil could you test with github action m0nsterrr/git-cliff-action@v1.6.0 ?

**Comment by lehmanju** [comment]
Would it be possible to supply the token via (non-required) input? I am trying to use this action on a on-premises enterprise github installation, so GITHUB_TOKEN exists but is obviously not authorized for github.com. I'd rather not use a token at all.

**Comment by lehmanju** [comment]
@M0NsTeRRR can confirm it works! Thx

**Comment by gdagil** [comment]
@M0NsTeRRR Yea, on gitea works too

**Comment by orhun** [comment]
Perfect! Thanks a lot everyone, release coming out shortly 🚀 ⛰️

**Comment by orhun** [comment]
https://github.com/orhun/git-cliff-action/releases/tag/v4.1.0
