### ISSUE TITLE
Not working when running inside container

### ISSUE THREAD

**Issue by lehmanju** [orhun/git-cliff-action#35]
Hey, unfortunately Github has a [bug](https://github.com/actions/runner/issues/2185) where the value of `github.action-path` is incorrect when running inside a container. Could you adjust this action to use the corresponding environment variable (`GITHUB_ACTION_PATH`) instead?

Otherwise I get an error that `install.sh` couldn't be found when using `container: <custom container image>`

**Comment by orhun** [comment]
Thanks for reporting! 🐻 should be fixesd in #36 and the new release will be out soon :)
