### ISSUE TITLE
wrong remote type detection 

### ISSUE THREAD

**Issue by Itsusinn** [orhun/git-cliff-action#39]
With GITHUB_REPO
But got
```
+ ./bin/git-cliff --config=.github/cliff.toml --latest --strip header
thread 'main' panicked at git-cliff-core/src/changelog.rs:458:18:
Could not get gitlab metadata: JsonError(Error("missing field `id`", line: 1, column: 35))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/Watfaq/clash-rs/actions/runs/11016979374/job/30597027807#step:8:3291

**Comment by orhun** [comment]
Thanks for reporting! It is now fixed in https://github.com/orhun/git-cliff/pull/885

Also I sent you a PR for properly adding the contributors to the changelog: https://github.com/Watfaq/clash-rs/pull/608
