### ISSUE TITLE
Action creating app git submodule in environment?

### ISSUE THREAD

**Issue by chamini2** [orhun/git-cliff-action#7]
From a short time we have had an `app` git submodule appearing in our release github actions: https://github.com/fal-ai/fal/actions/runs/3633307833/jobs/6130165436#step:9:22
Which results in the PR adding the submodule to the code: https://github.com/fal-ai/fal/pull/682/files#diff-a172cedcae47474b615c54d510a5d84a8dea3032e958587430b413538be3f333

I think it may be related to https://github.com/orhun/git-cliff-action/commit/4f2e0ab32036025ed2d1fa60192c1e169365689c

We noticed because when trying to build in our github action tests, we get build failures from this weird `app` git submodule: https://github.com/fal-ai/fal/pull/686

**Comment by chamini2** [comment]
confirmed, it no longer happens after https://github.com/fal-ai/fal/pull/696

**Comment by orhun** [comment]
Hey, I just released `1.2.1` with the potential fix. (It is no longer creating the "app" directory.)

Thanks for reporting! 🐻

**Comment by chamini2** [comment]
Awesome! I will try it later since I pinned to an earlier version. Thanks for taking a look!
