### ISSUE TITLE
Working directory permissions

### ISSUE THREAD

**Issue by w-bonelli** [orhun/git-cliff-action#8]
Thanks for developing this action. The [addition yesterday](https://github.com/orhun/git-cliff-action/commit/df3d46fac426fea3f6485bc308aad2ec8103ceab#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R8) of `chown -R root:root .` to the Docker container entrypoint alters filesystem permissions on the host, e.g. making subsequent workflow steps [unable to write to the job's working directory](https://github.com/w-bonelli/pycyapi/actions/runs/3751343145/jobs/6372217651#step:9:56).

**Comment by orhun** [comment]
Hey! 970cdaa65d3d3e8ad4d61bb01fb1172931eba8ba should fix this issue.

**Comment by w-bonelli** [comment]
thanks for the quick fix!
