### ISSUE TITLE
Permission Denied Error After Latest Update

### ISSUE THREAD

**Issue by zicklag** [orhun/git-cliff-action#9]
It looks like the latest update to this action might have caused a permission denied error in the Jumpy nightly job:

https://github.com/fishfolk/jumpy/actions/runs/4099380420/jobs/7069234818#step:5:229

It didn't happen yesterday, and I see there was a release made today. Do you have any idea what might be the cause or how to workaround?

**Comment by orhun** [comment]
It should be fine now. I reverted the faulty commit.
